language: generic
dist: xenial
addons:
  apt:
    update: true
    packages:
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - lmodern
      - texlive-luatex
      - texlive-xetex
      - fonts-hack-ttf
      - latexmk
script:
  - make p.pdf p-notes.pdf
